# Week 2 — Extra exercises: Titanic filters

Practise the same filtering operations introduced in Week 2: comparisons, conditions combined with `&` and `|`, and row filtering with column selection using `loc`.

Run the setup cell, then complete the exercises in order. Each exercise is independent: start from the original `df_titanic` every time. Display the matching rows; when specific columns are requested, show them in the listed order. Leave `df_titanic` unchanged.

Use parentheses around each condition combined with `&` or `|`. All exercises can be solved with the operations above.

## Setup

Use the `titanic.csv` supplied in `Week_2`. The cell below works when the notebook is run from `Week_2` or the repository root. In Colab, upload `titanic.csv` to the current session before running it.

In [1]:
from pathlib import Path
import pandas as pd

csv_path = Path("titanic.csv")
if not csv_path.is_file():
    csv_path = Path("Week_2") / "titanic.csv"
if not csv_path.is_file():
    raise FileNotFoundError("Place titanic.csv beside this notebook or run from the repository root.")

df_titanic = pd.read_csv(csv_path)

FileNotFoundError: Place titanic.csv beside this notebook or run from the repository root.

## Column reference

| Column | Meaning / values |
|---|---|
| `Name` | Passenger name. |
| `Sex` | `female` or `male`. |
| `Age` | Age in years; some values are missing. |
| `Pclass` | Ticket class: `1`, `2`, or `3`. |
| `Survived` | `1` = survived; `0` = did not survive. |
| `Fare` | Passenger fare. |
| `Embarked` | `C` = Cherbourg, `Q` = Queenstown, `S` = Southampton. |
| `SibSp` | Number of siblings and spouses aboard. |
| `Parch` | Number of parents and children aboard. |

For these exercises, **adult** means aged 18 or above. Missing ages do not satisfy the numeric age comparisons used here. Do not fill missing values.

## Single conditions

### F-01 — Second-class passengers

Select all passengers who travelled in second class (`Pclass` equal to `2`).

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("/usr/local/lib/python3.13/dist-packages/gradio/media_assets/data/titanic.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### F-02 — Passengers who did not survive

Select all passengers whose `Survived` value is `0`.

In [5]:
df[df['Survived'] == 0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### F-03 — Passengers under 18

Select all passengers younger than 18. Exclude passengers aged exactly 18.

In [6]:
df[df['Age'] < 18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

### F-04 — Fares of at least 50

Select all passengers whose `Fare` is greater than or equal to 50.

In [7]:
df[df['Fare'] >= 50]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

### F-05 — Passengers embarking at Queenstown

Select all passengers whose `Embarked` value is `Q`.

In [8]:
df[df['Embarked'] == 'Q']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
790,791,0,3,"Keane, Mr. Andrew ""Andy""",male,NaN,0,0,12460,7.7500,NaN,Q
825,826,0,3,"Flynn, Mr. John",male,NaN,0,0,368323,6.9500,NaN,Q
828,829,1,3,"McCormack, Mr. Thomas Joseph",male,NaN,0,0,367228,7.7500,NaN,Q
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Combining conditions with AND

### F-06 — Men in second class

Select passengers whose `Sex` is `male` **and** whose `Pclass` is `2`.

In [15]:
passageiros_masculinos_class2 = df[(df['Sex'] == 'male') & (df['Pclass'] == 2)]
passageiros_masculinos_class2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0,D56,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0,NaN,S
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S

### F-07 — Children who survived

Select passengers younger than 10 **and** who survived.

In [ ]:
# Your code here

### F-08 — Fares within a range

Select passengers who paid a fare from 10 to 30, **including both limits**. Use two comparisons combined with `&`.

In [ ]:
# Your code here

### F-09 — Adult passengers under 40

Select passengers aged at least 18 **and** younger than 40.

In [ ]:
# Your code here

### F-10 — No recorded close relatives aboard

Select passengers whose `SibSp` is `0` **and** whose `Parch` is `0`. This identifies passengers with no siblings, spouses, parents or children recorded aboard.

In [ ]:
# Your code here

## Combining conditions with OR

### F-11 — First or second class

Select passengers who travelled in first class **or** second class. Use two equality comparisons combined with `|`.

In [ ]:
# Your code here

### F-12 — Low or high fares

Select passengers whose fare is less than 10 **or** greater than 100. Exclude fares equal to either boundary.

In [16]:
df[df['Fare'].between(10, 100, inclusive='neither')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### F-13 — Recorded close relatives aboard

Select passengers whose `SibSp` is greater than `0` **or** whose `Parch` is greater than `0`.

In [ ]:
# Your code here

### F-14 — Young children or older adults

Select passengers younger than 6 **or** aged 65 and above.

In [ ]:
# Your code here

## Filtering rows and selecting columns

### F-15 — Women in second class

Select female passengers in second class. Use `loc` to show only `Name`, `Sex`, and `Pclass`.

In [ ]:
# Your code here

### F-16 — Children embarking at Southampton

Select passengers younger than 12 who embarked at Southampton (`S`). Use `loc` to show only `Name`, `Age`, and `Embarked`.

In [ ]:
# Your code here

### F-17 — Adult survivors with low fares

Select passengers aged 18 or above who survived and paid a fare less than 15. Use `loc` to show only `Name`, `Age`, `Fare`, and `Survived`.

In [ ]:
# Your code here

## Mixed conditions: AND and OR

### F-18 — Men embarking at two ports

Select male passengers who embarked at Cherbourg (`C`) **or** Southampton (`S`). The condition for `Sex` must apply to both ports. Use `loc` to show only `Name`, `Sex`, and `Embarked`.

In [ ]:
# Your code here

### F-19 — Survivors in an age range and two classes

Select passengers who satisfy **all** of the following:

- they survived;
- they were aged from 18 to 35, **including both limits**;
- they travelled in second **or** third class.

Store the combined condition in a variable, then use `loc` to show only `Name`, `Age`, `Pclass`, and `Survived`.

In [ ]:
filter_aged_18_35 = df['Age'].between(18,35, inclusive='both')
filter_pclass_2 = df['Pclass'] == 2
filter_pclass_3 = df['Pclass'] == 3
df.loc[filter_aged_18_35 & filter_passager_survived & filter_pclass_2 & filter_pclass_3]

### F-20 — Two passenger profiles

Select passengers who match **either** of these profiles:

- **Profile A:** female passengers in first class who survived;
- **Profile B:** male passengers in third class who did not survive and were aged 18 or above.

Create a condition for each profile, combine the two with `|`, then use `loc` to show only `Name`, `Sex`, `Age`, `Pclass`, and `Survived`.

In [18]:
# Your code here
filter_female = df['Sex'] == 'female'
filter_pclass_1 = df['Pclass'] == 1
filter_above_18 = df['Age'] >= 18
df[filter_female & filter_pclass_1].shape[0]

94